# Generated by Django 5.0.1 on 2024-12-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsubscription',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
