# Generated by Django 5.0.1 on 2024-12-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_restaurantsubscription_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsubscription',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
