# Generated by Django 5.0.1 on 2024-12-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_restaurantsubscription_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsubscription',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
