# Generated by Django 5.0.1 on 2024-12-20 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_restaurantsubscription_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurantForgotPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_reset_token', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('password_reset_expiration', models.DateTimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.restaurantsubscription')),
            ],
        ),
    ]
