# Generated by Django 5.0.1 on 2024-12-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_restaurantforgotpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantforgotpassword',
            name='password_reset_token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
