# Generated by Django 5.0.1 on 2024-12-20 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_restaurantforgotpassword_password_reset_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantforgotpassword',
            old_name='restaurant',
            new_name='restaurant_user',
        ),
    ]
