# Generated by Django 5.0.1 on 2025-01-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_rename_restaurant_restaurantforgotpassword_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsubscription',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='restaurantsubscription',
            name='plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantsubscription',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
