# Generated by Django 5.0.1 on 2024-12-26 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0007_rename_restaurant_restaurantforgotpassword_restaurant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurantMenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Home.restaurantsubscription')),
            ],
        ),
    ]
