# Generated by Django 5.0.1 on 2024-12-28 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurantMenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
                ('order_times', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Menu_Items', to='restau_panel.restaurantmenucategory')),
            ],
        ),
    ]
