# Generated by Django 5.0.1 on 2024-12-28 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_rename_restaurant_restaurantforgotpassword_restaurant_user'),
        ('restau_panel', '0002_restaurantmenuitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenuitems',
            name='item_taste',
            field=models.CharField(choices=[('Spicy', 'Spicy'), ('Medium Spicy', 'Medium Spicy')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantmenuitems',
            name='item_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantmenuitems',
            name='restaurant',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='Home.restaurantsubscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantmenuitems',
            name='date_of_add',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
