# Generated by Django 5.0.1 on 2024-12-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0003_restaurantmenuitems_item_taste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenuitems',
            name='date_of_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
