# Generated by Django 5.0.1 on 2024-12-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0004_alter_restaurantmenuitems_date_of_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenuitems',
            name='item_taste',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantmenuitems',
            name='item_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
