# Generated by Django 5.0.1 on 2024-12-28 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_rename_restaurant_restaurantforgotpassword_restaurant_user'),
        ('restau_panel', '0005_alter_restaurantmenuitems_item_taste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='QR_codes/')),
                ('qr_data', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.restaurantsubscription')),
            ],
        ),
    ]
