# Generated by Django 5.0.1 on 2024-12-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_rename_restaurant_restaurantforgotpassword_restaurant_user'),
        ('restau_panel', '0006_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='restaurantTable',
        ),
    ]
