# Generated by Django 5.0.1 on 2024-12-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0007_rename_table_restauranttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttable',
            name='number',
            field=models.IntegerField(),
        ),
    ]
