# Generated by Django 5.0.1 on 2024-12-28 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0008_alter_restauranttable_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
