# Generated by Django 5.0.1 on 2024-12-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0009_restauranttable_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttable',
            name='qr_data',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
