# Generated by Django 5.0.1 on 2024-12-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0011_order_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='restaurantOrder',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='restaurantOrderItem',
        ),
    ]
