# Generated by Django 5.0.1 on 2024-12-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0012_rename_order_restaurantorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
