# Generated by Django 5.0.1 on 2024-12-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0013_restaurantorder_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
