# Generated by Django 5.0.1 on 2024-12-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0014_restaurantorder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantorder',
            old_name='status',
            new_name='order_status',
        ),
    ]
