# Generated by Django 5.0.1 on 2024-12-30 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_rename_restaurant_restaurantforgotpassword_restaurant_user'),
        ('restau_panel', '0015_rename_status_restaurantorder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.restaurantsubscription'),
        ),
    ]
