# Generated by Django 5.0.1 on 2024-12-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0016_restaurantorder_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='table_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
