# Generated by Django 5.0.1 on 2025-01-01 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0017_restaurantorder_table_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantorder',
            old_name='table_number',
            new_name='table_Number',
        ),
        migrations.CreateModel(
            name='restaurantOrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restau_panel.restaurantorder')),
            ],
        ),
    ]
