# Generated by Django 5.0.1 on 2025-01-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0018_rename_table_number_restaurantorder_table_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantorderreview',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
