# Generated by Django 5.0.1 on 2025-01-01 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0019_alter_restaurantorderreview_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantorderreview',
            name='text',
        ),
        migrations.AddField(
            model_name='restaurantorderreview',
            name='review_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantorderreview',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restau_panel.restaurantorder'),
        ),
    ]
