# Generated by Django 5.0.1 on 2025-01-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0020_remove_restaurantorderreview_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantorderreview',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
