# Generated by Django 5.0.1 on 2025-01-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau_panel', '0021_alter_restaurantorderreview_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
